
 spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Surender-Vashisth/ididibank-config
          clone-on-start: true
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  cloud:
    config:
      server:
        default-profile: default
        port: 8083
        
        
